### PR TITLE
optional transitions to glacier

### PR DESCRIPTION
**Pull request by etwillbefine**
relates cloudposse/terraform-aws-cloudtrail-s3-bucket#17

### CODE REVIEW

**Comment by etwillbefine** [comment]
updated README with enable_glacier_transition

**Comment by etwillbefine** [comment]
Thanks for merging. Is there someone else needed or a different PR to wait for before doing the release?

**Comment by maximmi** [comment]
@etwillbefine sorry for delay, here is the release: https://github.com/cloudposse/terraform-aws-s3-log-storage/releases/tag/0.8.0

**Pull request merged**
