### PR TITLE
added versioning mfa delete enabled option

### LINKED ISSUE #48: Allow MFA delete option to be passed in
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[Slack Community](https://slack.cloudposse.com)

## Describe the Feature

The `aws_s3_bucket` resource allows an option in the `versioning` object for `mfa_delete`. It would be great to allow this option to be passed in.

## Expected Behavior

Set a variable for `versioning_mfa_delete` and the S3 bucket created will have MFA Delete enabled.

## Use Case

Security best practices for CloudTrail logs that are stored in S3 recommend MFA Delete be enabled.
- https://www.cloudconformity.com/knowledge-base/aws/CloudTrail/cloudtrail-bucket-mfa-delete-enabled.html

## Describe Ideal Solution

I can pass in a variable to this module that enables MFA Delete.

## Alternatives Considered

Write my own module, but I'd rather keep using this module. 🙂

### PR DESCRIPTION
**Pull request by chafnan**
## what
This adds the option to turn on MFA Delete for the bucket.
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
issue #48 does a good job explaining, but pasted important information below

Security best practices for CloudTrail logs that are stored in S3 recommend MFA Delete be enabled.
https://www.cloudconformity.com/knowledge-base/aws/CloudTrail/cloudtrail-bucket-mfa-delete-enabled.html 

## references
closes #48

### CODE REVIEW

**Comment by chafnan** [comment]
Withdrawing this PR for now, because it is not compatible with the lifecycle policy.  They don't play well together and need to research how to fix it correctly.

**Comment by chafnan** [comment]
Figured out how to handle the lifecycle policy with the MFA delete enabled.  Not sure if there are tests or something else that I missed for merging this. Please let me know and I'll get it fixed.

**Review by nitrocode — DISMISSED** [review]

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
